---
# Spine Switches Configuration
type: spine

# Spine-specific node definitions
spine:
  defaults:
    platform: cEOSLab
    loopback_ipv4_pool: 10.255.0.0/27
  nodes:
    - name: pulumi-spine1
      id: 1
      mgmt_ip: 172.16.1.11/24
      bgp_as: 65100
    - name: pulumi-spine2
      id: 2
      mgmt_ip: 172.16.1.12/24
      bgp_as: 65100
